import sgMail from '@sendgrid/mail'

const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY
const FROM = process.env.SENDGRID_FROM_EMAIL

export async function sendEmail(to: string, subject: string, text: string, options?: { html?: string; attachments?: { filename: string; content: string; type?: string }[] }) {
  if (!SENDGRID_API_KEY || !FROM) return { skipped: true }
  sgMail.setApiKey(SENDGRID_API_KEY)
  await sgMail.send({
    to,
    from: FROM,
    subject,
    text,
    html: options?.html,
    attachments: options?.attachments
  })
  return { ok: true }
}

export function buildInvoiceHtml(details: { auctionTitle: string; amount: number; buyerEmail: string; sellerEmail: string; auctionId: string }) {
  return `<!doctype html><html><body style="font-family:Arial,sans-serif">
  <h2>Invoice</h2>
  <p>Auction: <strong>${details.auctionTitle}</strong> (ID: ${details.auctionId})</p>
  <p>Amount: <strong>$${details.amount.toFixed(2)}</strong></p>
  <p>Buyer: ${details.buyerEmail}</p>
  <p>Seller: ${details.sellerEmail}</p>
  <hr/>
  <small>Generated by Auction System</small>
  </body></html>`
}
